#!/bin/bash
#
#$ -S /bin/bash

export MYAPP=./test_openmpi
export MYAPP_FLAGS=''

#$ -N TEST_OPENMPI 
#$ -pe openmpi_ib 4

. /etc/profile.d/modules.sh
# Load one of these
module add openmpi/gcc
# module add openmpi/psc
# module add openmpi/pgi
# module add openmpi/intel 


#$ -cwd
# $ -v MPI_HOME

# Does not require the -machinefile flag
CMD="$MPI_HOME/bin/mpirun -np $NSLOTS $MYAPP $MYAPP_FLAGS"

echo $CMD

$CMD
