name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: purge project
      run: cd project/parallelFEM && make purge
    - name: run demos
      run: cd project/parallelFEM && make demo

  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: purge project
      run: cd project/parallelFEM && make purge
    - name: run tests
      run: cd project/parallelFEM && make test
